apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-store
  namespace: music-store
  labels:
    app: music-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-store
  template:
    metadata:
      labels:
        app: music-store
    spec:
      containers:
        - name: music-store
          image: 788962775259.dkr.ecr.us-east-1.amazonaws.com/music-store-ecr
          imagePullPolicy: Always
          ports:
            - containerPort: 80
